env:
  es2017: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/react', 'plugin:react/recommended', 'prettier']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

rules:
  react/function-component-definitio: 0

settings:
  react:
    version: '16'
