env:
  es2017: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/react', 'plugin:react/recommended', 'prettier']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react']

rules:
  react/function-component-definition: 0
  arrow-body-style: 0
  indent: ["error", "tab", { "SwitchCase": 1 }]
  no-console: 0
  no-useless-escape: 0
  # no-unused-vars: 0

settings:
  react:
    version: '16'
